/* =============================================================
   data.js — generated by admin.html (the visual editor).
   Replace this file in your repo and commit to deploy.
   ============================================================= */

window.SITE = {
  "projects": [
    {
      "confidence": "0.99",
      "tag": "mask-count · vision",
      "title": "Mask Count",
      "description": "Real-time face-mask detection that scans a frame and counts how many people are masked versus unmasked.",
      "tech": [
        "Python",
        "OpenCV",
        "Detection"
      ],
      "video": "assets/videos/mask-count.mp4",
      "code": "https://github.com/Rishabh-creator601/Portfolio_projects",
      "codeLabel": "View code"
    },
    {
      "confidence": "0.97",
      "tag": "calorie-cnn · vision",
      "title": "Food Calorie Detection",
      "description": "A convolutional neural network that recognizes a dish from a photo and estimates its calorie content.",
      "tech": [
        "TensorFlow",
        "Keras",
        "CNN"
      ],
      "video": "assets/videos/food-calorie.mp4",
      "code": "https://github.com/Rishabh-creator601/Portfolio_projects/tree/master/food_calorie_cnn",
      "codeLabel": "View code"
    },
    {
      "confidence": "0.96",
      "tag": "flower-yolo · detection",
      "title": "Flower YOLO",
      "description": "A YOLO object-detection model trained to locate and classify flowers in a live video stream.",
      "tech": [
        "YOLOv11",
        "OpenCV",
        "Detection"
      ],
      "video": "assets/videos/flower-yolo.gif",
      "code": "https://github.com/Rishabh-creator601/Portfolio_projects/tree/master/flower_fiv_yolo",
      "codeLabel": "View code"
    },
    {
      "confidence": "0.95",
      "tag": "summarizer  · nlp",
      "title": "Transformer Summarizer + Document QA",
      "description": "Transformer-based tools that condense long documents and answer questions about what's inside them.",
      "tech": [
        "Transformers",
        "NLP",
        "FastAPI"
      ],
      "video": "assets/videos/transformer-summarizer.mp4",
      "code": "https://github.com/Rishabh-creator601/Portfolio_projects/tree/master/transformer_summarizer_documentqa",
      "codeLabel": "View code"
    },
    {
      "confidence": "0.95",
      "tag": "sentiment analysis· nlp",
      "title": "multi model sentiment analysis app ",
      "description": "NLP and Transformer-based Multi-Modal Sentiment Analysis App with the help of different sentiment models already available ",
      "tech": [
        "nlp",
        "sentiment analysis",
        "nltk",
        "vader",
        "text blob",
        "streamlit"
      ],
      "video": "assets\\videos\\multi model.gif ",
      "code": "https://github.com/Rishabh-creator601/Multi-Model-Sentiment-Analysis",
      "codeLabel": "View code"
    }
  ],
  "skills": [
    {
      "group": "Languages",
      "items": [
        {
          "name": "Python",
          "icon": "python"
        },
        {
          "name": "JavaScript",
          "icon": "javascript"
        },
        {
          "name": "C / C++",
          "icon": "cplusplus",
          "mono": "C++"
        },
        {
          "name": "HTML / CSS",
          "icon": "html5"
        },
        {
          "name": "Java",
          "icon": "",
          "mono": "JV"
        }
      ]
    },
    {
      "group": "ML / DL Frameworks",
      "items": [
        {
          "name": "TensorFlow",
          "icon": "tensorflow"
        },
        {
          "name": "Keras",
          "icon": "keras"
        },
        {
          "name": "Scikit-learn",
          "icon": "scikitlearn"
        }
      ]
    },
    {
      "group": "Computer Vision",
      "items": [
        {
          "name": "OpenCV",
          "icon": "opencv"
        },
        {
          "name": "YOLOv11",
          "icon": "",
          "mono": "YO"
        },
        {
          "name": "MediaPipe",
          "icon": "mediapipe"
        },
        {
          "name": "DeepFace",
          "icon": "",
          "mono": "DF"
        },
        {
          "name": "FaceNet",
          "icon": "",
          "mono": "FN"
        }
      ]
    },
    {
      "group": "NLP",
      "items": [
        {
          "name": "spaCy",
          "icon": "spacy"
        },
        {
          "name": "NLTK",
          "icon": "",
          "mono": "NL"
        },
        {
          "name": "HuggingFace Transformers",
          "icon": "huggingface"
        },
        {
          "name": "Gensim",
          "icon": "",
          "mono": "GS"
        }
      ]
    },
    {
      "group": "MLOps & APIs",
      "items": [
        {
          "name": "FastAPI",
          "icon": "fastapi"
        },
        {
          "name": "Pydantic",
          "icon": "pydantic"
        }
      ]
    },
    {
      "group": "Web & Deploy",
      "items": [
        {
          "name": "Streamlit",
          "icon": "streamlit"
        },
        {
          "name": "Flask",
          "icon": "flask"
        },
        {
          "name": "Next.js",
          "icon": "nextdotjs"
        },
        {
          "name": "Vercel",
          "icon": "vercel"
        }
      ]
    },
    {
      "group": "Tools & Platforms",
      "items": [
        {
          "name": "Git",
          "icon": "git"
        },
        {
          "name": "Google Colab",
          "icon": "googlecolab"
        },
        {
          "name": "Jupyter",
          "icon": "jupyter"
        },
        {
          "name": "VS Code",
          "icon": "",
          "mono": "VS"
        },
        {
          "name": "Kaggle",
          "icon": "kaggle"
        },
        {
          "name": "Obsidian",
          "icon": "obsidian"
        },
        {
          "name": "medium",
          "icon": "medium",
          "mono": ""
        }
      ]
    },
    {
      "group": "AI Copilots",
      "items": [
        {
          "name": "Claude",
          "icon": "claude"
        },
        {
          "name": "Google Gemini",
          "icon": "googlegemini"
        }
      ]
    }
  ],
  "roadmaps": [
    {
      "num": "01",
      "badge": "roadmap · 4 months",
      "title": "The roadmap that made me an AI/ML expert in just 4 months",
      "blurb": "The full path I followed to go from fundamentals to building real models in four months — what to learn, in what order, and what to skip.",
      "source": "Medium /h7w",
      "readTime": "~9 min",
      "link": "https://medium.com/h7w/roadmap-that-made-me-expert-in-aiml-in-just-4-months-c87bd191ead9?sharedUserId=rashesh369"
    },
    {
      "num": "02",
      "badge": "roadmap · 30 days",
      "title": "A practical AI/ML roadmap: beginner to professional in 30 days",
      "blurb": "A tighter, hands-on 30-day plan for people who want momentum fast — projects over theory, with the exact steps I took.",
      "source": "Medium /h7w",
      "readTime": "~11 min",
      "link": "https://medium.com/h7w/a-practical-ai-ml-roadmap-that-took-me-from-beginner-to-professional-in-30-days-1c48ce8ebeca?sharedUserId=rashesh369"
    }
  ],
  "mediumProfileUrl": "https://medium.com/@rashesh369",
  "mediumProfileLabel": "medium.com/@rashesh369",
  "links": [
    {
      "lk": "Email",
      "lv": "Email me !",
      "href": "mailto:rishabhagarwal1028@gmail.com"
    },
    {
      "lk": "GitHub",
      "lv": "@Rishabh-creator601",
      "href": "https://github.com/Rishabh-creator601"
    },
    {
      "lk": "Kaggle",
      "lv": "@rishabh2007",
      "href": "https://www.kaggle.com/rishabh2007/code?orderBy=dateUpdated"
    },
    {
      "lk": "Medium",
      "lv": "@rashesh369",
      "href": "https://medium.com/@rashesh369"
    },
    {
      "lk": "LinkedIn",
      "lv": "Rishabh Agarwal",
      "href": "https://www.linkedin.com/in/rishabh-agarwal-251373418/"
    }
  ]
};
